Fix for numpy.ndarray compare but repored in #110
Without the new `should_update` check, we get the error:
    ValueError: The truth value of an array with more than one element is ambiguous.
because numpy.ndarray objects cannot be compared with == and !=.
We choose to always update when new value is numpy.ndarray.